Bmpsublist.delete_all
Bmpsublist.create!({:id => 1,:name => "Autoirrigation/Autofertigation",:status => true,:bmplist_id => 1,:spanish_name => "Irrigacion/Fertirrigacion Automatica"}, :without_protection => true)
Bmpsublist.create!({:id => 2,:name => "Autofertigation",:status => true,:bmplist_id => 1,:spanish_name => "Fertirrigacion Automatica"}, :without_protection => true)
Bmpsublist.create!({:id => 3,:name => "Tile Drain",:status => true,:bmplist_id => 2,:spanish_name => "Sistema de Drenaje"}, :without_protection => true)
Bmpsublist.create!({:id => 4,:name => "Pads and Pipes",:status => true,:bmplist_id => 2,:spanish_name => "Almohadillas y Tuberias"}, :without_protection => true)
Bmpsublist.create!({:id => 5,:name => "Pads and Pipes - Two-Stage Ditch System",:status => true,:bmplist_id => 2,:spanish_name => "Almohadillas y Tuberias - Sistema de Zanja de Dos Etapas"}, :without_protection => true)
Bmpsublist.create!({:id => 6,:name => "Pads and Pipes - Ditch Enlargement and Reservoir System",:status => true,:bmplist_id => 2,:spanish_name => "Almohadillas y Tuberias - Ampliacion de la Zanja y Sistema de Represa"}, :without_protection => true)
Bmpsublist.create!({:id => 7,:name => "Pads and Pipes - Tailwater Irrigation",:status => true,:bmplist_id => 2,:spanish_name => "Almohadillas y Tuberias - Irrigacion desde Reserva"}, :without_protection => true)
Bmpsublist.create!({:id => 8,:name => "Wetlands",:status => true,:bmplist_id => 3,:spanish_name => "Humedales"}, :without_protection => true)
Bmpsublist.create!({:id => 9,:name => "Ponds",:status => true,:bmplist_id => 3,:spanish_name => "Lagunas"}, :without_protection => true)
Bmpsublist.create!({:id => 10,:name => "Stream Fencing (Livestock Access Control)",:status => true,:bmplist_id => 4,:spanish_name => "Cercado del rio (Control de Acceso del Ganado)"}, :without_protection => true)
Bmpsublist.create!({:id => 11,:name => "Streambank Stabilization",:status => true,:bmplist_id => 4,:spanish_name => "Estabilizacion de la Orilla del rio"}, :without_protection => true)
Bmpsublist.create!({:id => 12,:name => "Riparian Forest Buffer",:status => true,:bmplist_id => 4,:spanish_name => "Bosque Ribereno"}, :without_protection => true)
Bmpsublist.create!({:id => 13,:name => "Grass Buffer/Forest Buffer",:status => true,:bmplist_id => 4,:spanish_name => "Zona de Contencion Filtrante/Bosque Ribereno"}, :without_protection => true)
Bmpsublist.create!({:id => 14,:name => "Grass Waterway",:status => true,:bmplist_id => 4,:spanish_name => "Canal de Agua "}, :without_protection => true)
Bmpsublist.create!({:id => 15,:name => "Contour Buffer",:status => true,:bmplist_id => 5,:spanish_name => "Buffer de Contorno"}, :without_protection => true)
Bmpsublist.create!({:id => 16,:name => "Land Leveling",:status => true,:bmplist_id => 6,:spanish_name => "Nivelacion de la Tierra"}, :without_protection => true)
Bmpsublist.create!({:id => 17,:name => "Terrace System",:status => true,:bmplist_id => 6,:spanish_name => "Sistema de Terraza"}, :without_protection => true)
Bmpsublist.create!({:id => 18,:name => "Manure Control",:status => true,:bmplist_id => 6,:spanish_name => "Control de Estiercol"}, :without_protection => true)
Bmpsublist.create!({:id => 19,:name => "Cover Crop",:status => true,:bmplist_id => 9,:spanish_name => "Cultivo de Proteccion"}, :without_protection => true)
Bmpsublist.create!({:id => 20,:name => "Monthly Temperature and Precipitation Changes",:status => true,:bmplist_id => 7,:spanish_name => "Cambios de Temperatura y Precipitacion"}, :without_protection => true)
Bmpsublist.create!({:id => 21,:name => "Asphalt or Concrete",:status => true,:bmplist_id => 8,:spanish_name => "Asfalto o Concreto"}, :without_protection => true)
Bmpsublist.create!({:id => 22,:name => "Grass Cover",:status => true,:bmplist_id => 8,:spanish_name => "Cubierta de Pasto"}, :without_protection => true)
Bmpsublist.create!({:id => 23,:name => "Slope Adjustment",:status => true,:bmplist_id => 8,:spanish_name => "Ajuste de la inclinacion"}, :without_protection => true)
Bmpsublist.create!({:id => 24,:name => "Shading",:status => true,:bmplist_id => 8,:spanish_name => "Shading"}, :without_protection => true)
