CropSchedule.delete_all
CropSchedule.create!({:id => 1,:name => "Corn",:state_id => "*",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 2,:name => "Soybean",:state_id => "*",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 3,:name => "Barley, Cover Crop",:state_id => "*",:class_id => 2,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 4,:name => "Winter Wheat Cover Crop",:state_id => "*",:class_id => 2,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 8,:name => "Fallow",:state_id => "*",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 9,:name => "Wheat, Winter",:state_id => "*",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 10,:name => "Sorghum, Grain",:state_id => "*",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 11,:name => "Intensive (High)",:state_id => "*",:class_id => 3,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 13,:name => "Reduced (Low)",:state_id => "*",:class_id => 3,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 14,:name => "Apples",:state_id => "07,20,22,33,48",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 15,:name => "Potatoes",:state_id => "02,10,13,20,38,48",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 16,:name => "Grapes",:state_id => "05,33,48",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 17,:name => "Alfalfa",:state_id => "*",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 21,:name => "Triticale",:state_id => "*",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 22,:name => "Forest",:state_id => "*",:class_id => 1,:status => true}, :without_protection => true) 
CropSchedule.create!({:id => 23,:name => "Corn, Silage",:state_id => "*",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 24,:name => "Pasture, Improved",:state_id => "*",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 25,:name => "Cotton",:state_id => "01,03,04,05,10,11,19,25,26,32,34,37,41,43,44,47",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 26,:name => "Rice",:state_id => "04,05,19,25,26,44",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 27,:name => "Oats, Winter",:state_id => "04,20",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 28,:name => "Wheat, Spring",:state_id => "03,13,24,27,29,35,38,42,48",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 29,:name => "Blueberries",:state_id => "20,22,31",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 30,:name => "Dry Beans",:state_id => "10,13,23,35,48,51",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 36,:name => "Peanuts",:state_id => "01,10,11,34,41,44",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 37,:name => "Pecans",:state_id => "03,11,32,37",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 39,:name => "Sugarbeets",:state_id => "13,23,24,51",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 41,:name => "Sunflower",:state_id => "06,35,42",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 42,:name => "Tobacco",:state_id => "18,34",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 43,:name => "Walnut",:state_id => "05",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 48,:name => "Almonds",:state_id => "05",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 49,:name => "Barley",:state_id => "02,03,06,09,13,21,27,35,38,45,48,51",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 58,:name => "Rangeland",:state_id => "*",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 59,:name => "Pasture",:state_id => "*",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 60,:name => "Sorghum, Silage",:state_id => "*",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 61,:name => "Oats, Spring",:state_id => "02,20,33,39,50",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 62,:name => "Millet",:state_id => "6",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 64,:name => "Pasture, Winter",:state_id => "*",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 65,:name => "Bananas",:state_id => "52",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 66,:name => "Plantains",:state_id => "52",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 67,:name => "Big Bluestem Grass",:state_id => "17,37,44",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 68,:name => "Tomatoes",:state_id => "36",:class_id => 1,:status => true}, :without_protection => true)
