CropSchedule.delete_all
CropSchedule.create!({:id => 1,:name => "Corn",:state_id => "*",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 2,:name => "Soybean",:state_id => "*",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 3,:name => "Barley Cover Crop",:state_id => "*",:class_id => 2,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 4,:name => "Winter Wheat Cover Crop",:state_id => "*",:class_id => 2,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 5,:name => "Canola-Argentine",:state_id => "*",:class_id => 1,:status => false}, :without_protection => true)
CropSchedule.create!({:id => 6,:name => "Canadian Barley",:state_id => "*",:class_id => 1,:status => false}, :without_protection => true)
CropSchedule.create!({:id => 7,:name => "Field Peas",:state_id => "*",:class_id => 1,:status => false}, :without_protection => true)
CropSchedule.create!({:id => 8,:name => "Fallow",:state_id => "*",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 9,:name => "Winter Wheat",:state_id => "*",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 10,:name => "Grain Sorghum",:state_id => "*",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 11,:name => "Intensive (High)",:state_id => "*",:class_id => 3,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 12,:name => "Tillage Middle",:state_id => "*",:class_id => 3,:status => false}, :without_protection => true)
CropSchedule.create!({:id => 13,:name => "Reduced (Low)",:state_id => "*",:class_id => 3,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 14,:name => "Apples",:state_id => 48,:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 15,:name => "Potatoes",:state_id => 48,:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 16,:name => "Grapes, wine",:state_id => 48,:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 17,:name => "Alfalfa",:state_id => 48,:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 18,:name => "Corn, silage",:state_id => "48",:class_id => 1,:status => true}, :without_protection => true)
#CropSchedule.create!({:id => 19,:name => "Corn",:state_id => 48,:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 20,:name => "Winter wheat",:state_id => 48,:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 21,:name => "Triticale",:state_id => 48,:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 22,:name => "Forest",:state_id => "*",:class_id => 1,:status => true}, :without_protection => true) 
CropSchedule.create!({:id => 23,:name => "Corn silage",:state_id => "*",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 24,:name => "Bermuda Grass",:state_id => "*",:class_id => 1,:status => true}, :without_protection => true)
CropSchedule.create!({:id => 25,:name => "Cotton",:state_id => "*",:class_id => 1,:status => true}, :without_protection => true)