Fuel.delete_all
Fuel.create!({:id => 1,:description => "Gasoline (reformulated)",:code => "GAS"}, :without_protection => true)
Fuel.create!({:id => 2,:description => "Gasoline (reformulated)",:code => "GAS"}, :without_protection => true)
Fuel.create!({:id => 3,:description => "Gasoline blendstock",:code => "GASB"}, :without_protection => true)
Fuel.create!({:id => 4,:description => "DIESEL",:code => "DSL"}, :without_protection => true)
Fuel.create!({:id => 5,:description => "Soy based Biodiesel",:code => "SBDL"}, :without_protection => true)
Fuel.create!({:id => 6,:description => "Algae based Biodiesel",:code => "ABDL"}, :without_protection => true)
Fuel.create!({:id => 7,:description => "Propane	(LPG)",:code => "LPG"}, :without_protection => true)
Fuel.create!({:id => 8,:description => "Compressed Natural Gas (CNG)",:code => "CNG"}, :without_protection => true)
Fuel.create!({:id => 9,:description => "Compressed Land fill Gas (a CNG)",:code => "CLFG"}, :without_protection => true)
Fuel.create!({:id => 10,:description => "Liquefied Natural Gas (LNG)",:code => "LNG"}, :without_protection => true)
Fuel.create!({:id => 11,:description => "Liquefied Land Fill Gas (a LNG)",:code => "LLNG"}, :without_protection => true)
Fuel.create!({:id => 12,:description => "Corn based Ethanol",:code => "CETL"}, :without_protection => true)
Fuel.create!({:id => 13,:description => "Cellulosic Ethanol",:code => "ETLC"}, :without_protection => true)
Fuel.create!({:id => 14,:description => "Electricity",:code => "ELE"}, :without_protection => true)
Fuel.create!({:id => 15,:description => "Gaseous Hydrogen refueling",:code => "GHY1"}, :without_protection => true)
Fuel.create!({:id => 16,:description => "Gaseous Hydrogen central",:code => "GHY2"}, :without_protection => true)
Fuel.create!({:id => 17,:description => "Gaseous Hydrogen Electrolysis",:code => "GHY3"}, :without_protection => true)
Fuel.create!({:id => 18,:description => "Liquid Hydrogen refueling",:code => "LHY1"}, :without_protection => true)
Fuel.create!({:id => 19,:description => "Liquid Hydrogen central",:code => "LHY2"}, :without_protection => true)
Fuel.create!({:id => 20,:description => "Liquid Hydrogen electrolysis",:code => "LHY3"}, :without_protection => true)