State.delete_all
State.create!({:id => 1,:state_name => "Alabama",:state_code => "01",:status => 0,:state_abbreviation => "AL"}, :without_protection => true)
State.create!({:id => 2,:state_name => "Alaska",:state_code => "02",:status => 0,:state_abbreviation => "AK"}, :without_protection => true)
State.create!({:id => 3,:state_name => "Arizona",:state_code => "04",:status => 0,:state_abbreviation => "AZ"}, :without_protection => true)
State.create!({:id => 4,:state_name => "Arkansas",:state_code => "05",:status => 0,:state_abbreviation => "AR"}, :without_protection => true)
State.create!({:id => 5,:state_name => "California",:state_code => "06",:status => 1,:state_abbreviation => "CA"}, :without_protection => true)
State.create!({:id => 6,:state_name => "Colorado",:state_code => "08",:status => 0,:state_abbreviation => "CO"}, :without_protection => true)
State.create!({:id => 7,:state_name => "Connecticut",:state_code => "09",:status => 0,:state_abbreviation => "CT"}, :without_protection => true)
State.create!({:id => 8,:state_name => "District of Columbia",:state_code => "11",:status => 0,:state_abbreviation => "DC"}, :without_protection => true)
State.create!({:id => 9,:state_name => "Delaware",:state_code => "10",:status => 0,:state_abbreviation => "DE"}, :without_protection => true)
State.create!({:id => 10,:state_name => "Florida",:state_code => "12",:status => 0,:state_abbreviation => "FL"}, :without_protection => true)
State.create!({:id => 11,:state_name => "Georgia",:state_code => "13",:status => 0,:state_abbreviation => "GA"}, :without_protection => true)
State.create!({:id => 12,:state_name => "Hawaii",:state_code => "15",:status => 0,:state_abbreviation => "HI"}, :without_protection => true)
State.create!({:id => 13,:state_name => "Idaho",:state_code => "16",:status => 0,:state_abbreviation => "ID"}, :without_protection => true)
State.create!({:id => 14,:state_name => "Illinois",:state_code => "17",:status => 0,:state_abbreviation => "IL"}, :without_protection => true)
State.create!({:id => 15,:state_name => "Indiana",:state_code => "18",:status => 1,:state_abbreviation => "IN"}, :without_protection => true)
State.create!({:id => 16,:state_name => "Iowa",:state_code => "19",:status => 0,:state_abbreviation => "IA"}, :without_protection => true)
State.create!({:id => 17,:state_name => "Kansas",:state_code => "20",:status => 1,:state_abbreviation => "KS"}, :without_protection => true)
State.create!({:id => 18,:state_name => "Kentucky",:state_code => "21",:status => 1,:state_abbreviation => "KY"}, :without_protection => true)
State.create!({:id => 19,:state_name => "Louisiana",:state_code => "22",:status => 0,:state_abbreviation => "LA"}, :without_protection => true)
State.create!({:id => 20,:state_name => "Maine",:state_code => "23",:status => 0,:state_abbreviation => "ME"}, :without_protection => true)
State.create!({:id => 21,:state_name => "Maryland",:state_code => "24",:status => 1,:state_abbreviation => "MD"}, :without_protection => true)
State.create!({:id => 22,:state_name => "Massachusetts",:state_code => "25",:status => 0,:state_abbreviation => "MA"}, :without_protection => true)
State.create!({:id => 23,:state_name => "Michigan",:state_code => "26",:status => 1,:state_abbreviation => "MI"}, :without_protection => true)
State.create!({:id => 24,:state_name => "Minnesota",:state_code => "27",:status => 0,:state_abbreviation => "MN"}, :without_protection => true)
State.create!({:id => 25,:state_name => "Mississippi",:state_code => "28",:status => 0,:state_abbreviation => "MS"}, :without_protection => true)
State.create!({:id => 26,:state_name => "Missouri",:state_code => "29",:status => 1,:state_abbreviation => "MO"}, :without_protection => true)
State.create!({:id => 27,:state_name => "Montana",:state_code => "30",:status => 0,:state_abbreviation => "MT"}, :without_protection => true)
State.create!({:id => 28,:state_name => "Nebraska",:state_code => "31",:status => 0,:state_abbreviation => "NE"}, :without_protection => true)
State.create!({:id => 29,:state_name => "Nevada",:state_code => "32",:status => 0,:state_abbreviation => "NV"}, :without_protection => true)
State.create!({:id => 30,:state_name => "New Hampshire",:state_code => "33",:status => 0,:state_abbreviation => "NH"}, :without_protection => true)
State.create!({:id => 31,:state_name => "New Jersey",:state_code => "34",:status => 0,:state_abbreviation => "NJ"}, :without_protection => true)
State.create!({:id => 32,:state_name => "New Mexico",:state_code => "35",:status => 0,:state_abbreviation => "NM"}, :without_protection => true)
State.create!({:id => 33,:state_name => "New York",:state_code => "36",:status => 0,:state_abbreviation => "NY"}, :without_protection => true)
State.create!({:id => 34,:state_name => "North Carolina",:state_code => "37",:status => 0,:state_abbreviation => "NC"}, :without_protection => true)
State.create!({:id => 35,:state_name => "North Dakota",:state_code => "38",:status => 0,:state_abbreviation => "ND"}, :without_protection => true)
State.create!({:id => 36,:state_name => "Ohio",:state_code => "39",:status => 1,:state_abbreviation => "OH"}, :without_protection => true)
State.create!({:id => 37,:state_name => "Oklahoma",:state_code => "40",:status => 1,:state_abbreviation => "OK"}, :without_protection => true)
State.create!({:id => 38,:state_name => "Oregon",:state_code => "41",:status => 1,:state_abbreviation => "OR"}, :without_protection => true)
State.create!({:id => 39,:state_name => "Pennsylvania",:state_code => "42",:status => 0,:state_abbreviation => "PA"}, :without_protection => true)
State.create!({:id => 40,:state_name => "Rhode Island",:state_code => "44",:status => 0,:state_abbreviation => "RI"}, :without_protection => true)
State.create!({:id => 41,:state_name => "South Carolina",:state_code => "45",:status => 0,:state_abbreviation => "SC"}, :without_protection => true)
State.create!({:id => 42,:state_name => "South Dakota",:state_code => "46",:status => 0,:state_abbreviation => "SD"}, :without_protection => true)
State.create!({:id => 43,:state_name => "Tennessee",:state_code => "47",:status => 0,:state_abbreviation => "TN"}, :without_protection => true)
State.create!({:id => 44,:state_name => "Texas",:state_code => "48",:status => 1,:state_abbreviation => "TX"}, :without_protection => true)
State.create!({:id => 45,:state_name => "Utah",:state_code => "49",:status => 0,:state_abbreviation => "UT"}, :without_protection => true)
State.create!({:id => 46,:state_name => "Vermont",:state_code => "50",:status => 0,:state_abbreviation => "VT"}, :without_protection => true)
State.create!({:id => 47,:state_name => "Virginia",:state_code => "51",:status => 0,:state_abbreviation => "VA"}, :without_protection => true)
State.create!({:id => 48,:state_name => "Washington",:state_code => "53",:status => 1,:state_abbreviation => "WA"}, :without_protection => true)
State.create!({:id => 49,:state_name => "West Virginia",:state_code => "54",:status => 0,:state_abbreviation => "WV"}, :without_protection => true)
State.create!({:id => 50,:state_name => "Wisconsin",:state_code => "55",:status => 0,:state_abbreviation => "WI"}, :without_protection => true)
State.create!({:id => 51,:state_name => "Wyoming",:state_code => "56",:status => 0,:state_abbreviation => "WY"}, :without_protection => true)
State.create!({:id => 52,:state_name => "Puerto Rico",:state_code => "72",:status => 0,:state_abbreviation => "PR"}, :without_protection => true)

