#populate Parameters table.                                                                                                
Parameter.delete_all                                                                                                       
Parameter.create!({:id => 1, :number => 1, :default_value => 2, :state_id => 99}, :without_protection => true)             
Parameter.create!({:id => 2, :number => 2, :default_value => 2, :state_id => 99}, :without_protection => true)             
Parameter.create!({:id => 3, :number => 3, :default_value => 0.5, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 4, :number => 4, :default_value => 0.9, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 5, :number => 5, :default_value => 0.5	, :state_id => 99}, :without_protection => true)   
Parameter.create!({:id => 6, :number => 6, :default_value => 1, :state_id => 99}, :without_protection => true)             
Parameter.create!({:id => 7, :number => 7, :default_value => 0.9, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 8, :number => 8, :default_value => 20, :state_id => 99}, :without_protection => true)            
Parameter.create!({:id => 9, :number => 9, :default_value => 20, :state_id => 99}, :without_protection => true)            
Parameter.create!({:id => 10, :number => 10, :default_value => 20, :state_id => 99}, :without_protection => true)          
Parameter.create!({:id => 11, :number => 11, :default_value => -100, :state_id => 99}, :without_protection => true)        
Parameter.create!({:id => 12, :number => 12, :default_value => 2.5, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 13, :number => 13, :default_value => 2, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 14, :number => 14, :default_value => 0.2, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 15, :number => 15, :default_value => 0.05, :state_id => 99}, :without_protection => true)        
Parameter.create!({:id => 16, :number => 16, :default_value => 1, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 17, :number => 17, :default_value => 0.2, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 18, :number => 18, :default_value => 1.5, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 19, :number => 19, :default_value => 0.005, :state_id => 99}, :without_protection => true)       
Parameter.create!({:id => 20, :number => 20, :default_value => 0.2, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 21, :number => 21, :default_value => 10, :state_id => 99}, :without_protection => true)          
Parameter.create!({:id => 22, :number => 22, :default_value => 0.05, :state_id => 99}, :without_protection => true)        
Parameter.create!({:id => 23, :number => 23, :default_value => 0.0032, :state_id => 99}, :without_protection => true)      
Parameter.create!({:id => 24, :number => 24, :default_value => 0.1, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 25, :number => 25, :default_value => 0, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 26, :number => 26, :default_value => 0.05, :state_id => 99}, :without_protection => true)        
Parameter.create!({:id => 27, :number => 27, :default_value => 0.3, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 28, :number => 28, :default_value => 5, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 29, :number => 29, :default_value => 0.25, :state_id => 99}, :without_protection => true)        
Parameter.create!({:id => 30, :number => 30, :default_value => 1.4, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 31, :number => 31, :default_value => 0.3, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 32, :number => 32, :default_value => 1.25, :state_id => 99}, :without_protection => true)        
Parameter.create!({:id => 33, :number => 33, :default_value => 2, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 34, :number => 34, :default_value => 0.6, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 35, :number => 35, :default_value => 1.01, :state_id => 99}, :without_protection => true)        
Parameter.create!({:id => 36, :number => 36, :default_value => 0.001, :state_id => 99}, :without_protection => true)       
Parameter.create!({:id => 37, :number => 37, :default_value => 0.6, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 38, :number => 38, :default_value => 1, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 39, :number => 39, :default_value => 0.00001, :state_id => 99}, :without_protection => true)     
Parameter.create!({:id => 40, :number => 40, :default_value => 0.001, :state_id => 99}, :without_protection => true)       
Parameter.create!({:id => 41, :number => 41, :default_value => 0.5, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 42, :number => 42, :default_value => 1.8, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 43, :number => 43, :default_value => 0.0508, :state_id => 99}, :without_protection => true)      
Parameter.create!({:id => 44, :number => 44, :default_value => 1.5, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 45, :number => 45, :default_value => 3, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 46, :number => 46, :default_value => 0.7, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 47, :number => 47, :default_value => 1, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 48, :number => 48, :default_value => 0, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 49, :number => 49, :default_value => 5, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 50, :number => 50, :default_value => 1, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 51, :number => 51, :default_value => 0.5, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 52, :number => 52, :default_value => 10, :state_id => 99}, :without_protection => true)          
Parameter.create!({:id => 53, :number => 53, :default_value => 0.9, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 54, :number => 54, :default_value => 0.78, :state_id => 99}, :without_protection => true)        
Parameter.create!({:id => 55, :number => 55, :default_value => 0.2468, :state_id => 99}, :without_protection => true)      
Parameter.create!({:id => 56, :number => 56, :default_value => 0.9, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 57, :number => 57, :default_value => 0.78, :state_id => 99}, :without_protection => true)        
Parameter.create!({:id => 58, :number => 58, :default_value => 0.2468, :state_id => 99}, :without_protection => true)      
Parameter.create!({:id => 59, :number => 59, :default_value => 1, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 60, :number => 60, :default_value => 5, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 61, :number => 61, :default_value => 0.8, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 62, :number => 62, :default_value => 0.1, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 63, :number => 63, :default_value => 0.1, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 64, :number => 64, :default_value => 1, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 65, :number => 65, :default_value => 0.001, :state_id => 99}, :without_protection => true)       
Parameter.create!({:id => 66, :number => 66, :default_value => 1, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 67, :number => 67, :default_value => 10, :state_id => 99}, :without_protection => true)          
Parameter.create!({:id => 68, :number => 68, :default_value => 0.25, :state_id => 99}, :without_protection => true)        
Parameter.create!({:id => 69, :number => 69, :default_value => 1, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 70, :number => 70, :default_value => 1, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 71, :number => 71, :default_value => 1.15, :state_id => 99}, :without_protection => true)        
Parameter.create!({:id => 72, :number => 72, :default_value => 0.1, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 73, :number => 73, :default_value => 0.2, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 74, :number => 74, :default_value => 0.1, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 75, :number => 75, :default_value => 0.05, :state_id => 99}, :without_protection => true)        
Parameter.create!({:id => 76, :number => 76, :default_value => 0.005, :state_id => 99}, :without_protection => true)       
Parameter.create!({:id => 77, :number => 77, :default_value => 0, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 78, :number => 78, :default_value => 100, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 79, :number => 79, :default_value => 1, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 80, :number => 80, :default_value => 1, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 81, :number => 81, :default_value => 0, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 82, :number => 82, :default_value => 0, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 83, :number => 83, :default_value => 1, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 84, :number => 84, :default_value => 0.0001, :state_id => 99}, :without_protection => true)      
Parameter.create!({:id => 85, :number => 85, :default_value => 0.0001, :state_id => 99}, :without_protection => true)      
Parameter.create!({:id => 86, :number => 86, :default_value => 0.1, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 87, :number => 87, :default_value => 0.001, :state_id => 99}, :without_protection => true)       
Parameter.create!({:id => 88, :number => 88, :default_value => 0.001, :state_id => 99}, :without_protection => true)       
Parameter.create!({:id => 89, :number => 89, :default_value => 0.1, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 90, :number => 90, :default_value => 2, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 91, :number => 91, :default_value => 0.1, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 92, :number => 92, :default_value => 1, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 93, :number => 93, :default_value => 1, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 94, :number => 94, :default_value => 1, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 95, :number => 95, :default_value => 1, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 96, :number => 96, :default_value => 10, :state_id => 99}, :without_protection => true)          
Parameter.create!({:id => 97, :number => 97, :default_value => 1, :state_id => 99}, :without_protection => true)           
Parameter.create!({:id => 98, :number => 98, :default_value => 0.45, :state_id => 99}, :without_protection => true)        
Parameter.create!({:id => 99, :number => 99, :default_value => 0.5, :state_id => 99}, :without_protection => true)         
Parameter.create!({:id => 100, :number => 1, :default_value => 2, :state_id => 36}, :without_protection => true)           
Parameter.create!({:id => 101, :number => 2, :default_value => 2, :state_id => 36}, :without_protection => true)           
Parameter.create!({:id => 102, :number => 3, :default_value => 0.5, :state_id => 36}, :without_protection => true)         
Parameter.create!({:id => 103, :number => 4, :default_value => 0.8, :state_id => 36}, :without_protection => true)         
Parameter.create!({:id => 104, :number => 5, :default_value => 0.5	, :state_id => 36}, :without_protection => true)   
Parameter.create!({:id => 105, :number => 6, :default_value => 1, :state_id => 36}, :without_protection => true)           
Parameter.create!({:id => 106, :number => 7, :default_value => 0.9, :state_id => 36}, :without_protection => true)         
Parameter.create!({:id => 107, :number => 8, :default_value => 20, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 108, :number => 9, :default_value => 20, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 109, :number => 10, :default_value => 20, :state_id => 36}, :without_protection => true)         
Parameter.create!({:id => 110, :number => 11, :default_value => -100, :state_id => 36}, :without_protection => true)       
Parameter.create!({:id => 111, :number => 12, :default_value => 2.5, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 112, :number => 13, :default_value => 2, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 113, :number => 14, :default_value => 0.2, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 114, :number => 15, :default_value => 0.05, :state_id => 36}, :without_protection => true)       
Parameter.create!({:id => 115, :number => 16, :default_value => 1, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 116, :number => 17, :default_value => 0.2, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 117, :number => 18, :default_value => 1.5, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 118, :number => 19, :default_value => 0.03, :state_id => 36}, :without_protection => true)       
Parameter.create!({:id => 119, :number => 20, :default_value => 0.2, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 120, :number => 21, :default_value => 10, :state_id => 36}, :without_protection => true)         
Parameter.create!({:id => 121, :number => 22, :default_value => 0.05, :state_id => 36}, :without_protection => true)       
Parameter.create!({:id => 122, :number => 23, :default_value => 0.0032, :state_id => 36}, :without_protection => true)     
Parameter.create!({:id => 123, :number => 24, :default_value => 0.1, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 124, :number => 25, :default_value => 0, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 125, :number => 26, :default_value => 0.05, :state_id => 36}, :without_protection => true)       
Parameter.create!({:id => 126, :number => 27, :default_value => 0.3, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 127, :number => 28, :default_value => 5, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 128, :number => 29, :default_value => 0.25, :state_id => 36}, :without_protection => true)       
Parameter.create!({:id => 129, :number => 30, :default_value => 1.4, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 130, :number => 31, :default_value => 0.3, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 131, :number => 32, :default_value => 1.25, :state_id => 36}, :without_protection => true)       
Parameter.create!({:id => 132, :number => 33, :default_value => 2, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 133, :number => 34, :default_value => 0.6, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 134, :number => 35, :default_value => 1.01, :state_id => 36}, :without_protection => true)       
Parameter.create!({:id => 135, :number => 36, :default_value => 0.001, :state_id => 36}, :without_protection => true)      
Parameter.create!({:id => 136, :number => 37, :default_value => 0.7, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 137, :number => 38, :default_value => 1, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 138, :number => 39, :default_value => 0.00001, :state_id => 36}, :without_protection => true)    
Parameter.create!({:id => 139, :number => 40, :default_value => 0.001, :state_id => 36}, :without_protection => true)      
Parameter.create!({:id => 140, :number => 41, :default_value => 0.5, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 141, :number => 42, :default_value => 1.8, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 142, :number => 43, :default_value => 0.0508, :state_id => 36}, :without_protection => true)     
Parameter.create!({:id => 143, :number => 44, :default_value => 1.5, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 144, :number => 45, :default_value => 3, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 145, :number => 46, :default_value => 0.5, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 146, :number => 47, :default_value => 1, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 147, :number => 48, :default_value => 0, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 148, :number => 49, :default_value => 5, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 149, :number => 50, :default_value => 1, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 150, :number => 51, :default_value => 0.5, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 151, :number => 52, :default_value => 10, :state_id => 36}, :without_protection => true)         
Parameter.create!({:id => 152, :number => 53, :default_value => 0.9, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 153, :number => 54, :default_value => 0.78, :state_id => 36}, :without_protection => true)       
Parameter.create!({:id => 154, :number => 55, :default_value => 0.2468, :state_id => 36}, :without_protection => true)     
Parameter.create!({:id => 155, :number => 56, :default_value => 0.9, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 156, :number => 57, :default_value => 0.78, :state_id => 36}, :without_protection => true)       
Parameter.create!({:id => 157, :number => 58, :default_value => 0.2468, :state_id => 36}, :without_protection => true)     
Parameter.create!({:id => 158, :number => 59, :default_value => 1, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 159, :number => 60, :default_value => 5, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 160, :number => 61, :default_value => 0.8, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 161, :number => 62, :default_value => 0.1, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 162, :number => 63, :default_value => 0.1, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 163, :number => 64, :default_value => 1, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 164, :number => 65, :default_value => 0.001, :state_id => 36}, :without_protection => true)      
Parameter.create!({:id => 165, :number => 66, :default_value => 1, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 166, :number => 67, :default_value => 10, :state_id => 36}, :without_protection => true)         
Parameter.create!({:id => 167, :number => 68, :default_value => 0.25, :state_id => 36}, :without_protection => true)       
Parameter.create!({:id => 168, :number => 69, :default_value => 1, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 169, :number => 70, :default_value => 1, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 170, :number => 71, :default_value => 1.15, :state_id => 36}, :without_protection => true)       
Parameter.create!({:id => 171, :number => 72, :default_value => 0.1, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 172, :number => 73, :default_value => 0.2, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 173, :number => 74, :default_value => 0.1, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 174, :number => 75, :default_value => 0.05, :state_id => 36}, :without_protection => true)       
Parameter.create!({:id => 175, :number => 76, :default_value => 0.005, :state_id => 36}, :without_protection => true)      
Parameter.create!({:id => 176, :number => 77, :default_value => 0, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 177, :number => 78, :default_value => 100, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 178, :number => 79, :default_value => 1, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 179, :number => 80, :default_value => 1, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 180, :number => 81, :default_value => 0, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 181, :number => 82, :default_value => 0, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 182, :number => 83, :default_value => 0.8, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 183, :number => 84, :default_value => 0.0001, :state_id => 36}, :without_protection => true)     
Parameter.create!({:id => 184, :number => 85, :default_value => 0.0001, :state_id => 36}, :without_protection => true)     
Parameter.create!({:id => 185, :number => 86, :default_value => 0.1, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 186, :number => 87, :default_value => 0.001, :state_id => 36}, :without_protection => true)      
Parameter.create!({:id => 187, :number => 88, :default_value => 0.001, :state_id => 36}, :without_protection => true)      
Parameter.create!({:id => 188, :number => 89, :default_value => 0.1, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 189, :number => 90, :default_value => 2, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 190, :number => 91, :default_value => 0.1, :state_id => 36}, :without_protection => true)        
Parameter.create!({:id => 191, :number => 92, :default_value => 1, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 192, :number => 93, :default_value => 1, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 193, :number => 94, :default_value => 1, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 194, :number => 95, :default_value => 1, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 195, :number => 96, :default_value => 10, :state_id => 36}, :without_protection => true)         
Parameter.create!({:id => 196, :number => 97, :default_value => 1, :state_id => 36}, :without_protection => true)          
Parameter.create!({:id => 197, :number => 98, :default_value => 0.45, :state_id => 36}, :without_protection => true)       
Parameter.create!({:id => 198, :number => 99, :default_value => 0.5, :state_id => 36}, :without_protection => true)        
                                                                                                                           
                                                                                                                           
Control.delete_all                                                                                                         
Control.create!({:id => 1, :number => 1, :default_value => 0, :state_id => 99 }, :without_protection => true)              
Control.create!({:id => 2, :number => 2, :default_value => 1, :state_id => 99 }, :without_protection => true)              
Control.create!({:id => 3, :number => 3, :default_value => 1, :state_id => 99 }, :without_protection => true)              
Control.create!({:id => 4, :number => 4, :default_value => 1, :state_id => 99 }, :without_protection => true)              
Control.create!({:id => 5, :number => 5, :default_value => 3, :state_id => 99 }, :without_protection => true)              
Control.create!({:id => 6, :number => 6, :default_value => 2, :state_id => 99 }, :without_protection => true)              
Control.create!({:id => 7, :number => 7, :default_value => 0, :state_id => 99 }, :without_protection => true)              
Control.create!({:id => 8, :number => 8, :default_value => 0, :state_id => 99 }, :without_protection => true)              
Control.create!({:id => 9, :number => 9, :default_value => 0, :state_id => 99 }, :without_protection => true)              
Control.create!({:id => 10, :number => 10, :default_value => 4, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 11, :number => 11, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 12, :number => 12, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 13, :number => 13, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 14, :number => 14, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 15, :number => 15, :default_value => 4, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 16, :number => 16, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 17, :number => 17, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 18, :number => 18, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 19, :number => 19, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 20, :number => 20, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 21, :number => 21, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 22, :number => 22, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 23, :number => 23, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 24, :number => 24, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 25, :number => 25, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 26, :number => 26, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 27, :number => 27, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 28, :number => 28, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 29, :number => 29, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 30, :number => 30, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 31, :number => 31, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 32, :number => 32, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 33, :number => 33, :default_value => 1	, :state_id => 99 }, :without_protection => true)          
Control.create!({:id => 34, :number => 34, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 35, :number => 35, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 36, :number => 36, :default_value => 1, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 37, :number => 37, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 38, :number => 38, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 39, :number => 39, :default_value => 0.8, :state_id => 99 }, :without_protection => true)          
Control.create!({:id => 40, :number => 40, :default_value => 365, :state_id => 99 }, :without_protection => true)          
Control.create!({:id => 41, :number => 41, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 42, :number => 42, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 43, :number => 43, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 44, :number => 44, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 45, :number => 45, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 46, :number => 46, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 47, :number => 47, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 48, :number => 48, :default_value => 0.1, :state_id => 99 }, :without_protection => true)          
Control.create!({:id => 49, :number => 49, :default_value => 1, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 50, :number => 50, :default_value => 20, :state_id => 99 }, :without_protection => true)           
Control.create!({:id => 51, :number => 51, :default_value => 0.01, :state_id => 99 }, :without_protection => true)         
Control.create!({:id => 52, :number => 52, :default_value => 50	, :state_id => 99 }, :without_protection => true)          
Control.create!({:id => 53, :number => 53, :default_value => 10, :state_id => 99 }, :without_protection => true)           
Control.create!({:id => 54, :number => 54, :default_value => 0.4, :state_id => 99 }, :without_protection => true)          
Control.create!({:id => 55, :number => 55, :default_value => 1, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 56, :number => 56, :default_value => 2, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 57, :number => 57, :default_value => 2, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 58, :number => 58, :default_value => 90, :state_id => 99 }, :without_protection => true)           
Control.create!({:id => 59, :number => 59, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 60, :number => 60, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 61, :number => 61, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 62, :number => 62, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 63, :number => 63, :default_value => 50, :state_id => 99 }, :without_protection => true)           
Control.create!({:id => 64, :number => 64, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 65, :number => 65, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 66, :number => 66, :default_value => 1, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 67, :number => 67, :default_value => 10, :state_id => 99 }, :without_protection => true)           
Control.create!({:id => 68, :number => 68, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 69, :number => 69, :default_value => 4, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 70, :number => 70, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 71, :number => 71, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 72, :number => 72, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 73, :number => 73, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 74, :number => 74, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 75, :number => 75, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 76, :number => 76, :default_value => 0, :state_id => 99 }, :without_protection => true)            
Control.create!({:id => 77, :number => 1, :default_value => 0, :state_id => 36 }, :without_protection => true)             
Control.create!({:id => 78, :number => 2, :default_value => 1, :state_id => 36 }, :without_protection => true)             
Control.create!({:id => 79, :number => 3, :default_value => 1	, :state_id => 36 }, :without_protection => true)          
Control.create!({:id => 80, :number => 4, :default_value => 1, :state_id => 36 }, :without_protection => true)             
Control.create!({:id => 81, :number => 5, :default_value => 3, :state_id => 36 }, :without_protection => true)             
Control.create!({:id => 82, :number => 6, :default_value => 2, :state_id => 36 }, :without_protection => true)             
Control.create!({:id => 83, :number => 7, :default_value => 0, :state_id => 36 }, :without_protection => true)             
Control.create!({:id => 84, :number => 8, :default_value => 0, :state_id => 36 }, :without_protection => true)             
Control.create!({:id => 85, :number => 9, :default_value => 0, :state_id => 36 }, :without_protection => true)             
Control.create!({:id => 86, :number => 10, :default_value => 4, :state_id => 36 }, :without_protection => true)            
Control.create!({:id => 87, :number => 11, :default_value => 0, :state_id => 36 }, :without_protection => true)            
Control.create!({:id => 88, :number => 12, :default_value => 0, :state_id => 36 }, :without_protection => true)            
Control.create!({:id => 89, :number => 13, :default_value => 0, :state_id => 36 }, :without_protection => true)            
Control.create!({:id => 90, :number => 14, :default_value => 0, :state_id => 36 }, :without_protection => true)            
Control.create!({:id => 91, :number => 15, :default_value => 4, :state_id => 36 }, :without_protection => true)            
Control.create!({:id => 92, :number => 16, :default_value => 0, :state_id => 36 }, :without_protection => true)            
Control.create!({:id => 93, :number => 17, :default_value => 0, :state_id => 36 }, :without_protection => true)            
Control.create!({:id => 94, :number => 18, :default_value => 0, :state_id => 36 }, :without_protection => true)            
Control.create!({:id => 95, :number => 19, :default_value => 0, :state_id => 36 }, :without_protection => true)            
Control.create!({:id => 96, :number => 20, :default_value => 0, :state_id => 36 }, :without_protection => true)            
Control.create!({:id => 97, :number => 21, :default_value => 0, :state_id => 36 }, :without_protection => true)            
Control.create!({:id => 98, :number => 22, :default_value => 0, :state_id => 36 }, :without_protection => true)            
Control.create!({:id => 99, :number => 23, :default_value => 0, :state_id => 36 }, :without_protection => true)            
Control.create!({:id => 100, :number => 24, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 101, :number => 25, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 102, :number => 26, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 103, :number => 27, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 104, :number => 28, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 105, :number => 29, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 106, :number => 30, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 107, :number => 31, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 108, :number => 32, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 109, :number => 33, :default_value => 1	, :state_id => 36 }, :without_protection => true)          
Control.create!({:id => 110, :number => 34, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 111, :number => 35, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 112, :number => 36, :default_value => 1, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 113, :number => 37, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 114, :number => 38, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 115, :number => 39, :default_value => 0.8, :state_id => 36 }, :without_protection => true)         
Control.create!({:id => 116, :number => 40, :default_value => 365, :state_id => 36 }, :without_protection => true)         
Control.create!({:id => 117, :number => 41, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 118, :number => 42, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 119, :number => 43, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 120, :number => 44, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 121, :number => 45, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 122, :number => 46, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 123, :number => 47, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 124, :number => 48, :default_value => 0.1, :state_id => 36 }, :without_protection => true)         
Control.create!({:id => 125, :number => 49, :default_value => 1, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 126, :number => 50, :default_value => 20, :state_id => 36 }, :without_protection => true)          
Control.create!({:id => 127, :number => 51, :default_value => 0.01, :state_id => 36 }, :without_protection => true)        
Control.create!({:id => 128, :number => 52, :default_value => 50, :state_id => 36 }, :without_protection => true)  
Control.create!({:id => 129, :number => 53, :default_value => 10, :state_id => 36 }, :without_protection => true)          
Control.create!({:id => 130, :number => 54, :default_value => 0.4, :state_id => 36 }, :without_protection => true)         
Control.create!({:id => 131, :number => 55, :default_value => 1, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 132, :number => 56, :default_value => 2, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 133, :number => 57, :default_value => 2, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 134, :number => 58, :default_value => 90, :state_id => 36 }, :without_protection => true)          
Control.create!({:id => 135, :number => 59, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 136, :number => 60, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 137, :number => 61, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 138, :number => 62, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 139, :number => 63, :default_value => 5, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 140, :number => 64, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 141, :number => 65, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 142, :number => 66, :default_value => 1, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 143, :number => 67, :default_value => 10, :state_id => 36 }, :without_protection => true)          
Control.create!({:id => 144, :number => 68, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 145, :number => 69, :default_value => 4, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 146, :number => 70, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 147, :number => 71, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 148, :number => 72, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 149, :number => 73, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 150, :number => 74, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 151, :number => 75, :default_value => 0, :state_id => 36 }, :without_protection => true)           
Control.create!({:id => 152, :number => 76, :default_value => 0, :state_id => 36 }, :without_protection => true)           

#populate Parameters table.
ParameterDescription.delete_all
ParameterDescription.create!({:id => 1, :line => 1, :number => 1 , :name => 'Crop canopy-PET(1-2)', :range_low => 1, :range_high => 2}, :without_protection => true)
ParameterDescription.create!({:id => 2, :line => 1, :number => 2 , :name => 'Root growth_soil strength (1_2)', :range_low => 1, :range_high => 2}, :without_protection => true)
ParameterDescription.create!({:id => 3, :line => 1, :number => 3 , :name => 'Water stress_harvest index (0_1)', :range_low => 0, :range_high => 1}, :without_protection => true)
ParameterDescription.create!({:id => 4, :line => 1, :number => 4 , :name => 'Water storage N leaching (0_1)', :range_low => 0, :range_high => 1}, :without_protection => true)
ParameterDescription.create!({:id => 5, :line => 1, :number => 5 , :name => 'Soil water lower limit (0_1)', :range_low => 0, :range_high => 1}, :without_protection => true)
ParameterDescription.create!({:id => 6, :line => 1, :number => 6 , :name => 'Winter dormancy (h) (0_1)', :range_low => 0, :range_high => 1}, :without_protection => true)
ParameterDescription.create!({:id => 7, :line => 1, :number => 7 , :name => 'N fixation (0_1)', :range_low => 0, :range_high => 1}, :without_protection => true)
ParameterDescription.create!({:id => 8, :line => 1, :number => 8 , :name => 'Soluble p runoff coefficient. (1*m^3/t)', :range_low => 10, :range_high => 20}, :without_protection => true)
ParameterDescription.create!({:id => 9, :line => 1, :number => 9 , :name => 'Pest damage moisture threshold', :range_low => 25, :range_high => 150}, :without_protection => true)
ParameterDescription.create!({:id => 10, :line => 1, :number => 10, :name => 'Pest damage cover threshold', :range_low => 1, :range_high => 10}, :without_protection => true)
ParameterDescription.create!({:id => 11, :line => 2, :number => 11, :name => 'Moisture required for seed germination', :range_low => 10, :range_high => 30}, :without_protection => true)
ParameterDescription.create!({:id => 12, :line => 2, :number => 12, :name => 'Soil evaporation coefficient', :range_low => 1.5, :range_high => 2.5}, :without_protection => true)
ParameterDescription.create!({:id => 13, :line => 2, :number => 13, :name => 'Wind erodibility coefficient', :range_low => 0, :range_high => 3}, :without_protection => true)
ParameterDescription.create!({:id => 14, :line => 2, :number => 14, :name => 'Nitrate leaching ratio', :range_low => 0.1, :range_high => 1}, :without_protection => true)
ParameterDescription.create!({:id => 15, :line => 2, :number => 15, :name => 'Runoff CN weighting factor (0.0 1.0)', :range_low => 0, :range_high => 1}, :without_protection => true)
ParameterDescription.create!({:id => 16, :line => 2, :number => 16, :name => 'Expands CN retention parameter (1.0 1.5)', :range_low => 1, :range_high => 1.5}, :without_protection => true)
ParameterDescription.create!({:id => 17, :line => 2, :number => 17, :name => 'Soil evaporation plant cover factor (0.0 0.5)', :range_low => 0, :range_high => 0.5}, :without_protection => true)
ParameterDescription.create!({:id => 18, :line => 2, :number => 18, :name => 'Sediment routing exponent(1_1.5)', :range_low => 1, :range_high => 1.5}, :without_protection => true)
ParameterDescription.create!({:id => 19, :line => 2, :number => 19, :name => 'Sediment routing coefficient', :range_low => 0.01, :range_high => 0.05}, :without_protection => true)
ParameterDescription.create!({:id => 20, :line => 2, :number => 20, :name => 'Runoff curve number initial abstraction (0.05_0.4)', :range_low => 0.05, :range_high => 0.4}, :without_protection => true)
ParameterDescription.create!({:id => 21, :line => 3, :number => 21, :name => 'Soluble C absorption Coefficient (0.1*M^3/T) (10_20)', :range_low => 10, :range_high => 20}, :without_protection => true)
ParameterDescription.create!({:id => 22, :line => 3, :number => 22, :name => 'Reduce NRCS runoff CN retention parameter for frozen soils (0.05_0.5)', :range_low => 0.05, :range_high => 0.5}, :without_protection => true)
ParameterDescription.create!({:id => 23, :line => 3, :number => 23, :name => 'Hargreaves PET equation coefficient (0.0023_0.0032)', :range_low => 0.0023, :range_high => 0.0032}, :without_protection => true)
ParameterDescription.create!({:id => 24, :line => 3, :number => 24, :name => 'Pesticide leaching ratio (0.1_1)', :range_low => 0.1, :range_high => 1.1}, :without_protection => true)
ParameterDescription.create!({:id => 25, :line => 3, :number => 25, :name => 'Exponential Coeficient Used to account for rainfall intensity on CN', :range_low => 0, :range_high => 2}, :without_protection => true)
ParameterDescription.create!({:id => 26, :line => 3, :number => 26, :name => 'Fraction of maturity at spring growth initiation (0_1)', :range_low => 0, :range_high => 1}, :without_protection => true)
ParameterDescription.create!({:id => 27, :line => 3, :number => 27, :name => 'CEC effect on nitrification and volatilization (0_1)', :range_low => 0, :range_high => 1.3}, :without_protection => true)
ParameterDescription.create!({:id => 28, :line => 3, :number => 28, :name => 'Limit of nitrogen fixation by legums (0.1-10)(kg/ha/day)', :range_low => 0.1, :range_high => 10}, :without_protection => true)
ParameterDescription.create!({:id => 29, :line => 3, :number => 29, :name => 'Biological mixing efficiency (0.1_0.5)', :range_low => 0.1, :range_high => 0.5}, :without_protection => true)
ParameterDescription.create!({:id => 30, :line => 3, :number => 30, :name => 'Soluble p runoff exponent(1_1.5)', :range_low => 1, :range_high => 1.5}, :without_protection => true)
ParameterDescription.create!({:id => 31, :line => 4, :number => 31, :name => 'Maximum depth for biological mixing', :range_low => 0.1, :range_high => 0.3}, :without_protection => true)
ParameterDescription.create!({:id => 32, :line => 4, :number => 32, :name => 'Organic N and P sediment transport exponent', :range_low => 1, :range_high => 1.5}, :without_protection => true)
ParameterDescription.create!({:id => 33, :line => 4, :number => 33, :name => 'Coefficient to calculate Soil Erosion for MUST Driving Equation', :range_low => 2, :range_high => 3}, :without_protection => true)
ParameterDescription.create!({:id => 34, :line => 4, :number => 34, :name => 'Hargreaves PET equation exp (0.5_0.6)', :range_low => 0.5, :range_high => 0.6}, :without_protection => true)
ParameterDescription.create!({:id => 35, :line => 4, :number => 35, :name => 'Denitrification soil_water threshold (.9_1.1)', :range_low => 0.9, :range_high => 1.1}, :without_protection => true)
ParameterDescription.create!({:id => 36, :line => 4, :number => 36, :name => 'Denitrification rate constant(.1_2)', :range_low => 0.1, :range_high => 2}, :without_protection => true)
ParameterDescription.create!({:id => 37, :line => 4, :number => 37, :name => 'Exponent in Delivery Ratio for SWAT Output (0.1_0.6)', :range_low => 0, :range_high => 2}, :without_protection => true)
ParameterDescription.create!({:id => 38, :line => 4, :number => 38, :name => 'Water stress weighting coefficient (0_1)', :range_low => 0, :range_high => 1}, :without_protection => true)
ParameterDescription.create!({:id => 39, :line => 4, :number => 39, :name => 'Puddling saturated conductiviy (mm/h) (0.00001_0.1)', :range_low => 0.00001, :range_high => 0.1}, :without_protection => true)
ParameterDescription.create!({:id => 40, :line => 4, :number => 40, :name => 'Groundwater storage threshold(.001_1.)', :range_low => 0.001, :range_high => 1}, :without_protection => true)
ParameterDescription.create!({:id => 41, :line => 5, :number => 41, :name => 'Plant root temperature stress exp(.1_2.)', :range_low => 0.1, :range_high => 2}, :without_protection => true)
ParameterDescription.create!({:id => 42, :line => 5, :number => 42, :name => 'SCS curve number index coefficient.5_1.5)', :range_low => 0.5, :range_high => 1.5}, :without_protection => true)
ParameterDescription.create!({:id => 43, :line => 5, :number => 43, :name => 'Plow layer depth(m)', :range_low => 0, :range_high => 999}, :without_protection => true)
ParameterDescription.create!({:id => 44, :line => 5, :number => 44, :name => 'Upper limit of curve number retention parameter S (1_2)', :range_low => 1, :range_high => 2}, :without_protection => true)
ParameterDescription.create!({:id => 45, :line => 5, :number => 45, :name => 'Sediment routing travel time coefficient', :range_low => 0.5, :range_high => 10}, :without_protection => true)
ParameterDescription.create!({:id => 46, :line => 5, :number => 46, :name => 'RUSLE c factor coefficient (.5_1.5)', :range_low => 0.5, :range_high => 1.5}, :without_protection => true)
ParameterDescription.create!({:id => 47, :line => 5, :number => 47, :name => 'RUSLE c factor coefficient (.5_1.5)', :range_low => 0.5, :range_high => 1.5}, :without_protection => true)
ParameterDescription.create!({:id => 48, :line => 5, :number => 48, :name => 'adjusts climatic stress factor (aap/aat)', :range_low => 50, :range_high => 80}, :without_protection => true)
ParameterDescription.create!({:id => 49, :line => 5, :number => 49, :name => 'maximum rainfall interception by plant canopy (mm) (2._15.)', :range_low => 2, :range_high => 15}, :without_protection => true)
ParameterDescription.create!({:id => 50, :line => 5, :number => 50, :name => 'rainfall interception coefficient', :range_low => 0.05, :range_high => 0.3}, :without_protection => true)
ParameterDescription.create!({:id => 51, :line => 6, :number => 51, :name => 'water stored in litter (residue) coefficient (.1_.9).', :range_low => 0.1, :range_high => 0.9}, :without_protection => true)
ParameterDescription.create!({:id => 52, :line => 6, :number => 52, :name => 'Exponential coefficient in EQUATION Expresing tillage effect on resi', :range_low => 5, :range_high => 15}, :without_protection => true)
ParameterDescription.create!({:id => 53, :line => 6, :number => 53, :name => 'Coefficient in oxygen EQUATION used in modifying microbial activity (0.8_0.95)', :range_low => 0.8, :range_high => 0.95}, :without_protection => true)
ParameterDescription.create!({:id => 54, :line => 6, :number => 54, :name => 'N enrichment ratio coefficient for routing (.3_0.9)', :range_low => 0.4, :range_high => 0.7}, :without_protection => true)
ParameterDescription.create!({:id => 55, :line => 6, :number => 55, :name => 'N enrichment ratio exp for routing (.1_.3)', :range_low => 0.1, :range_high => 0.3}, :without_protection => true)
ParameterDescription.create!({:id => 56, :line => 6, :number => 56, :name => 'Fraction destroyed by burn operation (.5_1.)', :range_low => 0.5, :range_high => 1}, :without_protection => true)
ParameterDescription.create!({:id => 57, :line => 6, :number => 57, :name => 'P enrichment ratio coefficient for routing (.05_.2)', :range_low => 0.05, :range_high => 0.2}, :without_protection => true)
ParameterDescription.create!({:id => 58, :line => 6, :number => 58, :name => 'P enrichment ratio exp for routing (.3_.9)', :range_low => 0.2, :range_high => 0.4}, :without_protection => true)
ParameterDescription.create!({:id => 59, :line => 6, :number => 59, :name => 'P upward movement by evaporation coefficient (1_20)', :range_low => 1, :range_high => 20}, :without_protection => true)
ParameterDescription.create!({:id => 60, :line => 6, :number => 60, :name => 'Maximum number of days a pasture is grazed before rotation (1_365)', :range_low => 1, :range_high => 365}, :without_protection => true)
ParameterDescription.create!({:id => 61, :line => 7, :number => 61, :name => 'Soil water Upward Flow Limit (0.05_0.95)', :range_low => 0, :range_high => 1.8}, :without_protection => true)
ParameterDescription.create!({:id => 62, :line => 7, :number => 62, :name => 'Manure erosion equation coefficient', :range_low => 0.1, :range_high => 0.5}, :without_protection => true)
ParameterDescription.create!({:id => 63, :line => 7, :number => 63, :name => 'N Enrichment Ratio for Delivery of SWAT (0.8_1.2)', :range_low => 0.1, :range_high => 1.1}, :without_protection => true)
ParameterDescription.create!({:id => 64, :line => 7, :number => 64, :name => 'Dust distribution coefficient', :range_low => 0.5, :range_high => 1.5}, :without_protection => true)
ParameterDescription.create!({:id => 65, :line => 7, :number => 65, :name => 'RUSLE2 transport capacity parameter (0.001_0.1)', :range_low => 0.001, :range_high => 0.1}, :without_protection => true)
ParameterDescription.create!({:id => 66, :line => 7, :number => 66, :name => 'RUSLE2 Threshold transport capacity coeffient (1.0_10.0)', :range_low => 1, :range_high => 10}, :without_protection => true)
ParameterDescription.create!({:id => 67, :line => 7, :number => 67, :name => 'Dust distribution dispersion exponent (5.0_15.0)', :range_low => 5, :range_high => 15}, :without_protection => true)
ParameterDescription.create!({:id => 68, :line => 7, :number => 68, :name => 'Manure erosion exponent t(0.1_1.0)', :range_low => 0.1, :range_high => 1}, :without_protection => true)
ParameterDescription.create!({:id => 69, :line => 7, :number => 69, :name => 'Coefficient adjusts microbial activity function in top soil layer (0.1_1.0)', :range_low => 0.1, :range_high => 1.5}, :without_protection => true)
ParameterDescription.create!({:id => 70, :line => 7, :number => 70, :name => 'Microbial decay rate coefficient (0.5_1.5)', :range_low => 0.5, :range_high => 1.5}, :without_protection => true)
ParameterDescription.create!({:id => 71, :line => 8, :number => 71, :name => 'Manure erosion coefficient (1.0_1.5)', :range_low => 1, :range_high => 1.5}, :without_protection => true)
ParameterDescription.create!({:id => 72, :line => 8, :number => 72, :name => 'Volatilization/nitrification partitioning coefficient (0.05_0.5)', :range_low => 0.05, :range_high => 0.5}, :without_protection => true)
ParameterDescription.create!({:id => 73, :line => 8, :number => 73, :name => 'Hydrograph development parameter (0.1_0.9)', :range_low => 0.1, :range_high => 0.9}, :without_protection => true)
ParameterDescription.create!({:id => 74, :line => 8, :number => 74, :name => 'Partitions Nitrogen flow from groundwater (0.0_20)', :range_low => 0.01, :range_high => 0.05}, :without_protection => true)
ParameterDescription.create!({:id => 75, :line => 8, :number => 75, :name => 'P Enrichment Ratio for Delivery to SWAT (0.05_1.5)', :range_low => 0.01, :range_high => 0.05}, :without_protection => true)
ParameterDescription.create!({:id => 76, :line => 8, :number => 76, :name => 'Standing dead fall rate Coef(0.0001_0.1)', :range_low => 1, :range_high => 1.5}, :without_protection => true)
ParameterDescription.create!({:id => 77, :line => 8, :number => 77, :name => 'Runoff amount to delay pest application(mm)(Range from 0-25)', :range_low => 0, :range_high => 25}, :without_protection => true)
ParameterDescription.create!({:id => 78, :line => 8, :number => 78, :name => 'Soil water value to delay tillage(Range from 0-1)', :range_low => 0, :range_high => 1}, :without_protection => true)
ParameterDescription.create!({:id => 79, :line => 8, :number => 79, :name => 'Auto Mow lower limit(t/ha)(0.2-3.0)', :range_low => 0, :range_high => 999}, :without_protection => true)
ParameterDescription.create!({:id => 80, :line => 8, :number => 80, :name => 'Upper Limit of Nitrification-Volatilization (0.0_0.5)', :range_low => 10, :range_high => 20}, :without_protection => true)
ParameterDescription.create!({:id => 81, :line => 9, :number => 81, :name => 'Technology Coeficient (0.0_0.01)', :range_low => 0, :range_high => 0.01}, :without_protection => true)
ParameterDescription.create!({:id => 82, :line => 9, :number => 82, :name => 'Not Used', :range_low => 0, :range_high => 0}, :without_protection => true)
ParameterDescription.create!({:id => 83, :line => 9, :number => 83, :name => 'Estimates drainage system lateral hydraulic conductivity (0.1_10.0)', :range_low => 0.1, :range_high => 10}, :without_protection => true)
ParameterDescription.create!({:id => 84, :line => 9, :number => 84, :name => 'Coefficient regulating P Flux between labile and active pool (0.0001_0.001)', :range_low => 0.0001, :range_high => 0.001}, :without_protection => true)
ParameterDescription.create!({:id => 85, :line => 9, :number => 85, :name => 'Coefficient regulating P Flux between active and active pool (0.0001_0.001)', :range_low => 0.0001, :range_high => 0.001}, :without_protection => true)
ParameterDescription.create!({:id => 86, :line => 9, :number => 86, :name => 'Nitrogen and salt upward movement by evaporation coefficient (0.001_20.0)', :range_low => 0.01, :range_high => 20}, :without_protection => true)
ParameterDescription.create!({:id => 87, :line => 9, :number => 87, :name => 'Water table recession coefficient (0.001_1.0)', :range_low => 0.001, :range_high => 1}, :without_protection => true)
ParameterDescription.create!({:id => 88, :line => 9, :number => 88, :name => 'Limits daily water table movement (0.001_1.0)', :range_low => 0.001, :range_high => 1}, :without_protection => true)
ParameterDescription.create!({:id => 89, :line => 9, :number => 89, :name => 'Water table recession exponenet (0.1_0.9)', :range_low => 0.1, :range_high => 0.9}, :without_protection => true)
ParameterDescription.create!({:id => 90, :line => 9, :number => 90, :name => 'Subsurface flow factor (1.0_100)', :range_low => 1, :range_high => 100}, :without_protection => true)
ParameterDescription.create!({:id => 91, :line => 10, :number => 91, :name => 'Flood Evaporation Llimit (0.001_1.0)', :range_low => 0.001, :range_high => 1}, :without_protection => true)
ParameterDescription.create!({:id => 92, :line => 10, :number => 92, :name => 'Runoff Volume adjustment for direct link (NVCN=0) (0.1_2.0)', :range_low => 0.1, :range_high => 2}, :without_protection => true)
ParameterDescription.create!({:id => 93, :line => 10, :number => 93, :name => 'Water Erosion Threshold', :range_low => 0, :range_high => 10}, :without_protection => true)
ParameterDescription.create!({:id => 94, :line => 10, :number => 94, :name => 'Wind Erosion Threshold', :range_low => 0, :range_high => 10}, :without_protection => true)
ParameterDescription.create!({:id => 95, :line => 10, :number => 95, :name => '', :range_low => 0, :range_high => 999}, :without_protection => true)
ParameterDescription.create!({:id => 96, :line => 10, :number => 96, :name => '', :range_low => 0, :range_high => 999}, :without_protection => true)
ParameterDescription.create!({:id => 97, :line => 10, :number => 97, :name => 'Factor one to calculate fraction of humus in passive pool', :range_low => 0, :range_high => 999}, :without_protection => true)
ParameterDescription.create!({:id => 98, :line => 10, :number => 98, :name => 'Factor two to calculate fraction of humus in passive pool', :range_low => 0, :range_high => 999}, :without_protection => true)
ParameterDescription.create!({:id => 99, :line => 10, :number => 99, :name => '	Factor to calculate ground water storage', :range_low => 0, :range_high => 999}, :without_protection => true)

#populate Controls table
ControlDescription.delete_all
ControlDescription.create!({:id => 1, :line => 1, :column => 1, :code =>'NBYR', :name => 'Number years of simulation (0-100)', :range_low =>0, :range_high => 100}, :without_protection => true)
ControlDescription.create!({:id => 2, :line => 1, :column => 2, :code =>'IYR', :name => 'Beginning year of simulation (1-2040)', :range_low =>1, :range_high => 2040}, :without_protection => true)
ControlDescription.create!({:id => 3, :line => 1, :column => 3, :code =>'IMO', :name => 'Beginning month of simulation (1-12)', :range_low =>1, :range_high => 12}, :without_protection => true)
ControlDescription.create!({:id => 4, :line => 1, :column => 4, :code =>'IDA', :name => 'Beginning day of simulation (1-31)', :range_low =>1, :range_high => 31}, :without_protection => true)
ControlDescription.create!({:id => 5, :line => 1, :column => 5, :code =>'IPD', :name => 'Print code for type of output (0-9)', :range_low =>0, :range_high => 9}, :without_protection => true)
ControlDescription.create!({:id => 6, :line => 1, :column => 6, :code =>'NGN', :name => 'Input code for weather variable (-1 to 2345)', :range_low =>-1, :range_high => 2345}, :without_protection => true)
ControlDescription.create!({:id => 7, :line => 1, :column => 7, :code =>'IGN', :name => 'Number of times random number generator cycles before simulations starts (0-100)', :range_low =>0, :range_high => 100}, :without_protection => true)
ControlDescription.create!({:id => 8, :line => 1, :column => 8, :code =>'IGSD', :name => 'Day weather generator stops generation daily weather (-n to 366)', :range_low =>-366, :range_high => 366}, :without_protection => true)
ControlDescription.create!({:id => 9, :line => 1, :column => 9, :code =>'LPYR', :name => 'Leap year considered (0-1)', :range_low =>0, :range_high => 1}, :without_protection => true)
ControlDescription.create!({:id => 10, :line => 1, :column => 10, :code =>'IET', :name => 'Potential evapotranspiration equation (0-1)', :range_low =>0, :range_high => 5}, :without_protection => true)
ControlDescription.create!({:id => 11, :line => 1, :column => 11, :code =>'ISCN', :name => 'Stochastic CN estimator code (0-1)', :range_low =>0, :range_high => 1}, :without_protection => true)
ControlDescription.create!({:id => 12, :line => 1, :column => 12, :code =>'ITYP', :name => 'Peak rate estimate code (-1 to 4)', :range_low =>-1, :range_high => 4}, :without_protection => true)
ControlDescription.create!({:id => 13, :line => 1, :column => 13, :code =>'ISTA', :name => 'Static soil code (0-1)', :range_low =>0, :range_high => 1}, :without_protection => true)
ControlDescription.create!({:id => 14, :line => 1, :column => 14, :code =>'IHUS', :name => 'Automatic heat unit scheduling (0-1)', :range_low =>0, :range_high => 1}, :without_protection => true)
ControlDescription.create!({:id => 15, :line => 1, :column => 15, :code =>'NVCN', :name => 'Non-varying CN-CN2 used (0-4)', :range_low =>0, :range_high => 4}, :without_protection => true)
ControlDescription.create!({:id => 16, :line => 1, :column => 16, :code =>'INFL', :name => 'Runoff (Q) estimation methodology (0-3)', :range_low =>0, :range_high => 3}, :without_protection => true)
ControlDescription.create!({:id => 17, :line => 1, :column => 17, :code =>'MASP', :name => 'Pesticide output in mass and concentration (0-1)', :range_low =>0, :range_high => 1}, :without_protection => true)
ControlDescription.create!({:id => 18, :line => 1, :column => 18, :code =>'IERT', :name => 'Enrichment ration method (0-1)', :range_low =>0, :range_high => 1}, :without_protection => true)
ControlDescription.create!({:id => 19, :line => 1, :column => 19, :code =>'LBP', :name => 'Soluble P runoff estimate equation (0-2)', :range_low =>0, :range_high => 2}, :without_protection => true)
ControlDescription.create!({:id => 20, :line => 1, :column => 20, :code =>'NUPC', :name => 'N and P plant uptake concentration code (0-1)', :range_low =>0, :range_high => 1}, :without_protection => true)
ControlDescription.create!({:id => 21, :line => 2, :column => 1, :code =>'MNUL', :name => 'Manure application code (0-3)', :range_low =>0, :range_high => 3}, :without_protection => true)
ControlDescription.create!({:id => 22, :line => 2, :column => 2, :code =>'LPD', :name => 'Lagoon pumping (0-365)', :range_low =>0, :range_high => 365}, :without_protection => true)
ControlDescription.create!({:id => 23, :line => 2, :column => 3, :code =>'MSCP', :name => 'Solid manure scraping (0-365)', :range_low =>0, :range_high => 365}, :without_protection => true)
ControlDescription.create!({:id => 24, :line => 2, :column => 4, :code =>'ISLF', :name => 'Slope length/steepness factor (0-1)', :range_low =>0, :range_high => 1}, :without_protection => true)
ControlDescription.create!({:id => 25, :line => 2, :column => 5, :code =>'NAQ', :name => 'Air quality analysis (0-1)', :range_low =>0, :range_high => 1}, :without_protection => true)
ControlDescription.create!({:id => 26, :line => 2, :column => 6, :code =>'IHY', :name => 'Flood routing (0-1)', :range_low =>0, :range_high => 1}, :without_protection => true)
ControlDescription.create!({:id => 27, :line => 2, :column => 7, :code =>'ICO2', :name => 'Atmospheric CO2 (0-1)', :range_low =>0, :range_high => 1}, :without_protection => true)
ControlDescription.create!({:id => 28, :line => 2, :column => 8, :code =>'ISW', :name => 'Field capacity/wilting point estimation (0-3)', :range_low =>0, :range_high => 3}, :without_protection => true)
ControlDescription.create!({:id => 29, :line => 2, :column => 9, :code =>'IGMX', :name => 'Number of times generator seeds are initialized for a site (1-100)', :range_low =>1, :range_high => 100}, :without_protection => true)
ControlDescription.create!({:id => 30, :line => 2, :column => 10, :code =>'IDIR', :name => 'Data directory', :range_low =>0, :range_high => 1}, :without_protection => true)
ControlDescription.create!({:id => 31, :line => 2, :column => 11, :code =>'IMW', :name => 'MIN INTERVAL BETWEEN AUTO MOW', :range_low =>0, :range_high => 0}, :without_protection => true)
ControlDescription.create!({:id => 32, :line => 2, :column => 11, :code =>'IOX', :name => 'O2 -- depth function', :range_low =>0, :range_high => 1}, :without_protection => true)
ControlDescription.create!({:id => 33, :line => 2, :column => 12, :code =>'IDNT', :name => 'Denitrification parameter (0-1)', :range_low =>0, :range_high => 1}, :without_protection => true)
ControlDescription.create!({:id => 34, :line => 2, :column => 14, :code =>'IAZM', :name => 'Latitude source', :range_low =>0, :range_high => 1}, :without_protection => true)
ControlDescription.create!({:id => 35, :line => 2, :column => 15, :code =>'IPAT', :name => 'Auto-Phosphorous Switch', :range_low =>0, :range_high => 1}, :without_protection => true)
ControlDescription.create!({:id => 36, :line => 2, :column => 16, :code =>'IHRD', :name => 'Grazing Mode', :range_low =>0, :range_high => 2}, :without_protection => true)
ControlDescription.create!({:id => 37, :line => 2, :column => 17, :code =>'IWTB', :name => 'Duraton of antecedent period for rainfall and PET accumulation to drive water table', :range_low =>99999, :range_high => 0}, :without_protection => true)
ControlDescription.create!({:id => 38, :line => 2, :column => 18, :code =>'ISAP', :name => 'Subarea Number (1-1000)', :range_low =>1, :range_high => 1000}, :without_protection => true)
ControlDescription.create!({:id => 39, :line => 3, :column => 1, :code =>'RFN', :name => 'Average concentration of nitrogen in rainfall (Range: 0.5-1.5)', :range_low =>0.5, :range_high => 1.5 }, :without_protection => true)
ControlDescription.create!({:id => 40, :line => 3, :column => 2, :code =>'CO2', :name => 'Carbon dioxide concentration in atmosphere (Range: 0-1000)', :range_low =>0, :range_high => 1000 }, :without_protection => true)
ControlDescription.create!({:id => 41, :line => 3, :column => 3, :code =>'CQN', :name => 'Concentration of NO3-N in irrigation water in ppm (Range: 0-1000)', :range_low =>0, :range_high => 1000}, :without_protection => true)
ControlDescription.create!({:id => 42, :line => 3, :column => 4, :code =>'PSTX', :name => 'Pest damage scaling factor (Range: 0-10)', :range_low =>0, :range_high => 10}, :without_protection => true)
ControlDescription.create!({:id => 43, :line => 3, :column => 5, :code =>'YWI', :name => 'Number years of maximum monthly 0.5 hour rainfall available. (Range: 0-20)', :range_low =>0, :range_high => 20}, :without_protection => true)
ControlDescription.create!({:id => 44, :line => 3, :column => 6, :code =>'BTA', :name => 'COEF (0-1) governing wet-dry probabilities given days of rain (Range: 0-1)', :range_low =>0, :range_high => 1}, :without_protection => true)
ControlDescription.create!({:id => 45, :line => 3, :column => 7, :code =>'EXPK', :name => 'Parameter used to modify exponential rainfall amount distribution (Range: 0-2)', :range_low =>0, :range_high => 2}, :without_protection => true)
ControlDescription.create!({:id => 46, :line => 3, :column => 8, :code =>'QG', :name => 'Channel Capacity Flow Rate(1-100)BLANK if channel geometry is input by Channel bottom width/depth (BWD)', :range_low =>1, :range_high => 100}, :without_protection => true)
ControlDescription.create!({:id => 47, :line => 3, :column => 9, :code =>'QCF', :name => 'Exponent in watershed area flow rate equation (Range: 0.4-0.6)', :range_low =>0.4, :range_high => 0.6}, :without_protection => true)
ControlDescription.create!({:id => 48, :line => 3, :column => 10, :code =>'CHSO', :name => 'Average upland slope (m/m) in watershed (Range: 0.001-0.7)', :range_low =>0.001, :range_high => 0.7}, :without_protection => true)
ControlDescription.create!({:id => 49, :line => 4, :column => 1, :code =>'BWD', :name => 'Channel bottom width/depth in m/m; Channel flow rate (QG) (Range: 1-20)', :range_low =>1, :range_high => 20}, :without_protection => true)
ControlDescription.create!({:id => 50, :line => 4, :column => 2, :code =>'FCW', :name => 'Floodplain width/channel width in m/m (Range: 2-50)', :range_low =>2, :range_high => 50}, :without_protection => true)
ControlDescription.create!({:id => 51, :line => 4, :column => 3, :code =>'FPSC', :name => 'Floodplain saturated hydraulic conductivity in mm/h (Range: 0.0001-10)', :range_low =>0.0001, :range_high => 10}, :without_protection => true)
ControlDescription.create!({:id => 52, :line => 4, :column => 4, :code =>'GWSO', :name => 'Maximum ground water storage in mm (Range: 5-200)', :range_low =>5, :range_high => 200}, :without_protection => true)
ControlDescription.create!({:id => 53, :line => 4, :column => 5, :code =>'RFTO', :name => 'Ground water residence time in days (Range: 0-365)', :range_low =>0, :range_high => 365}, :without_protection => true)
ControlDescription.create!({:id => 54, :line => 4, :column => 6, :code =>'RFPO', :name => 'Return Flow / (Return Flow + Deep Percolation)(Range: 0-1)', :range_low =>0, :range_high => 1 }, :without_protection => true)
ControlDescription.create!({:id => 55, :line => 4, :column => 7, :code =>'SATO', :name => 'Saturated Conductivity adjustment factor(Use with Green and Ampt)(Range: 0.01-10)', :range_low =>0.01, :range_high => 10}, :without_protection => true)
ControlDescription.create!({:id => 56, :line => 4, :column => 8, :code =>'FL', :name => 'Field length (if wind erosion is to be considered)(Range: 0.001-12)', :range_low =>0.001, :range_high => 12}, :without_protection => true)
ControlDescription.create!({:id => 57, :line => 4, :column => 9, :code =>'FW', :name => 'Field width (if wind erosion is to be considered)(Range: 0.001-12)', :range_low =>0.001, :range_high => 12}, :without_protection => true)
ControlDescription.create!({:id => 58, :line => 4, :column => 10, :code =>'ANG', :name => 'Clockwise angle of field length from north (if wind erosion is to be considered)(Range: 0-360)', :range_low =>0, :range_high => 360 }, :without_protection => true)
ControlDescription.create!({:id => 59, :line => 5, :column => 1, :code =>'UXP', :name => 'Power Parameter of Modified Exponential Distribution of Wind Speed (if wind erosion is to be considered)(Range: 0-1)', :range_low =>0, :range_high => 1}, :without_protection => true)
ControlDescription.create!({:id => 60, :line => 5, :column => 2, :code =>'DIAM', :name => 'Soil Particle Diameter(if wind erosion is to be considered)(Range: 100-500)', :range_low =>100, :range_high => 500}, :without_protection => true)
ControlDescription.create!({:id => 61, :line => 5, :column => 3, :code =>'ACW', :name => 'Wind Erosion Adjustment Factor (Range: 0-10)', :range_low =>0, :range_high => 10}, :without_protection => true)
ControlDescription.create!({:id => 62, :line => 5, :column => 4, :code =>'GZL0', :name => 'Grazing limit(Range: 0.001-5.0)', :range_low =>0.001, :range_high => 5}, :without_protection => true)
ControlDescription.create!({:id => 63, :line => 5, :column => 5, :code =>'RTN0', :name => 'Number of years of cultivation at start of simulation (Range: 0-1000)', :range_low =>0, :range_high => 1000 }, :without_protection => true)
ControlDescription.create!({:id => 64, :line => 5, :column => 6, :code =>'BXCT', :name => 'Linear coefficient of change in rainfall from east to west (PI/PO/KM) Range: 0-1', :range_low =>0, :range_high => 1}, :without_protection => true)
ControlDescription.create!({:id => 65, :line => 5, :column => 7, :code =>'BYCT', :name => 'Linear coefficient of change in rainfall from south to north (PI/PO/KM)Range: 0-1', :range_low =>0, :range_high => 1}, :without_protection => true)
ControlDescription.create!({:id => 66, :line => 5, :column => 8, :code =>'DTHY', :name => 'Time interval for flood routing (hours)Range: 0.5-12', :range_low =>0.5, :range_high => 12}, :without_protection => true)
ControlDescription.create!({:id => 67, :line => 5, :column => 9, :code =>'QTH', :name => 'Routing Threshold (mm)VSC routing used when QVOL>QTH ) (Range: 0-200000)', :range_low =>0, :range_high => 200000}, :without_protection => true)
ControlDescription.create!({:id => 68, :line => 5, :column => 10, :code =>'STND', :name => 'VSC Routing used when reach storage > STND(Range: 0-200000)', :range_low =>0, :range_high => 200000}, :without_protection => true)
ControlDescription.create!({:id => 69, :line => 6, :column => 1, :code =>'DRV', :name => 'Equation for Water Erosion(Range: 0-7)', :range_low =>0, :range_high => 7}, :without_protection => true)
ControlDescription.create!({:id => 70, :line => 6, :column => 2, :code =>'PCO0', :name => 'Fraction of subareas controlled by ponds Range: 0-1', :range_low =>0, :range_high => 1}, :without_protection => true)
ControlDescription.create!({:id => 71, :line => 6, :column => 3, :code =>'RCC0', :name => 'USLE Crop management Channel Factor (0.0001_0.6)', :range_low =>0, :range_high => 0}, :without_protection => true)
ControlDescription.create!({:id => 72, :line => 6, :column => 4, :code =>'CSLT', :name => 'Salt concentration in irrigation water (ppm)', :range_low =>0, :range_high => 99999}, :without_protection => true)
ControlDescription.create!({:id => 73, :line => 6, :column => 5, :code =>'BUS(1)', :name => 'MUSI input according to equation above(Range: 0-10)', :range_low =>0, :range_high => 10}, :without_protection => true)
ControlDescription.create!({:id => 74, :line => 6, :column => 6, :code =>'BUS(2)', :name => 'MUSI input according to equation above(Range: 0-0.9)', :range_low =>0, :range_high => 0.9}, :without_protection => true)
ControlDescription.create!({:id => 75, :line => 6, :column => 7, :code =>'BUS(3)', :name => 'MUSI input according to equation above(Range: 0-0.9)', :range_low =>0, :range_high => 0.9}, :without_protection => true)
ControlDescription.create!({:id => 76, :line => 6, :column => 8, :code =>'BUS(4)', :name => 'MUSI input according to equation above(Range: 0-1.2)', :range_low =>0, :range_high => 1.2}, :without_protection => true)

