class AddAnimalTransportInputTripsToAplcatParameters < ActiveRecord::Migration
  def change
    add_column :aplcat_parameters, :trans_1, :integer
    add_column :aplcat_parameters, :categories_trans_1, :integer
    add_column :aplcat_parameters, :categories_slaug_1, :float
    add_column :aplcat_parameters, :avg_marweight_1, :integer
    add_column :aplcat_parameters, :num_animal_1, :integer
    add_column :aplcat_parameters, :mortality_rate_1, :float
    add_column :aplcat_parameters, :distance_1, :float
    add_column :aplcat_parameters, :trailer_1, :string
    add_column :aplcat_parameters, :trucks_1, :string
    add_column :aplcat_parameters, :fuel_type_1, :string
    add_column :aplcat_parameters, :same_vehicle_1, :integer
    add_column :aplcat_parameters, :loading_1, :integer
    add_column :aplcat_parameters, :carcass_1, :float
    add_column :aplcat_parameters, :boneless_beef_1, :float
    add_column :aplcat_parameters, :trans_2, :integer
    add_column :aplcat_parameters, :categories_trans_2, :integer
    add_column :aplcat_parameters, :categories_slaug_2, :float
    add_column :aplcat_parameters, :avg_marweight_2, :integer
    add_column :aplcat_parameters, :num_animal_2, :integer
    add_column :aplcat_parameters, :mortality_rate_2, :float
    add_column :aplcat_parameters, :distance_2, :float
    add_column :aplcat_parameters, :trailer_2, :string
    add_column :aplcat_parameters, :trucks_2, :string
    add_column :aplcat_parameters, :fuel_type_2, :string
    add_column :aplcat_parameters, :same_vehicle_2, :integer
    add_column :aplcat_parameters, :loading_2, :integer
    add_column :aplcat_parameters, :carcass_2, :float
    add_column :aplcat_parameters, :boneless_beef_2, :float
    add_column :aplcat_parameters, :trans_3, :integer
    add_column :aplcat_parameters, :categories_trans_3, :integer
    add_column :aplcat_parameters, :categories_slaug_3, :float
    add_column :aplcat_parameters, :avg_marweight_3, :integer
    add_column :aplcat_parameters, :num_animal_3, :integer
    add_column :aplcat_parameters, :mortality_rate_3, :float
    add_column :aplcat_parameters, :distance_3, :float
    add_column :aplcat_parameters, :trailer_3, :string
    add_column :aplcat_parameters, :trucks_3, :string
    add_column :aplcat_parameters, :fuel_type_3, :string
    add_column :aplcat_parameters, :same_vehicle_3, :integer
    add_column :aplcat_parameters, :loading_3, :integer
    add_column :aplcat_parameters, :carcass_3, :float
    add_column :aplcat_parameters, :boneless_beef_3, :float
    add_column :aplcat_parameters, :trans_4, :integer
    add_column :aplcat_parameters, :categories_trans_4, :integer
    add_column :aplcat_parameters, :categories_slaug_4, :float
    add_column :aplcat_parameters, :avg_marweight_4, :integer
    add_column :aplcat_parameters, :num_animal_4, :integer
    add_column :aplcat_parameters, :mortality_rate_4, :float
    add_column :aplcat_parameters, :distance_4, :float
    add_column :aplcat_parameters, :trailer_4, :string
    add_column :aplcat_parameters, :trucks_4, :string
    add_column :aplcat_parameters, :fuel_type_4, :string
    add_column :aplcat_parameters, :same_vehicle_4, :integer
    add_column :aplcat_parameters, :loading_4, :integer
    add_column :aplcat_parameters, :carcass_4, :float
    add_column :aplcat_parameters, :boneless_beef_4, :float
  end
end
