class AddEmissionInputToAplcatParameters < ActiveRecord::Migration[5.2]
  def change
    add_column :aplcat_parameters, :sixth_area, :integer
    add_column :aplcat_parameters, :sixth_equip, :integer
    add_column :aplcat_parameters, :sixth_fuel, :integer
    add_column :aplcat_parameters, :seventh_area, :integer
    add_column :aplcat_parameters, :seventh_equip, :integer
    add_column :aplcat_parameters, :seventh_fuel, :integer
    add_column :aplcat_parameters, :eighth_area, :integer
    add_column :aplcat_parameters, :eighth_equip, :integer
    add_column :aplcat_parameters, :eighth_fuel, :integer
    add_column :aplcat_parameters, :ninth_area, :integer
    add_column :aplcat_parameters, :ninth_equip, :integer
    add_column :aplcat_parameters, :ninth_fuel, :integer
    add_column :aplcat_parameters, :tenth_area, :integer
    add_column :aplcat_parameters, :tenth_equip, :integer
    add_column :aplcat_parameters, :tenth_fuel, :integer
    add_column :aplcat_parameters, :eleventh_area, :integer
    add_column :aplcat_parameters, :eleventh_equip, :integer
    add_column :aplcat_parameters, :eleventh_fuel, :integer
    add_column :aplcat_parameters, :twelveth_area, :integer
    add_column :aplcat_parameters, :twelveth_equip, :integer
    add_column :aplcat_parameters, :twelveth_fuel, :integer
    add_column :aplcat_parameters, :thirteen_area, :integer
    add_column :aplcat_parameters, :thirteen_equip, :integer
    add_column :aplcat_parameters, :thirteen_fuel, :integer
    add_column :aplcat_parameters, :fourteen_area, :integer
    add_column :aplcat_parameters, :fourteen_equip, :integer
    add_column :aplcat_parameters, :fourteen_fuel, :integer
    add_column :aplcat_parameters, :fifteen_area, :integer
    add_column :aplcat_parameters, :fifteen_equip, :integer
    add_column :aplcat_parameters, :fifteen_fuel, :integer
    add_column :aplcat_parameters, :sixteen_area, :integer
    add_column :aplcat_parameters, :sixteen_equip, :integer
    add_column :aplcat_parameters, :sixteen_fuel, :integer
    add_column :aplcat_parameters, :seventeen_area, :integer
    add_column :aplcat_parameters, :seventeen_equip, :integer
    add_column :aplcat_parameters, :seventeen_fuel, :integer
    add_column :aplcat_parameters, :eighteen_area, :integer
    add_column :aplcat_parameters, :eighteen_equip, :integer
    add_column :aplcat_parameters, :eighteen_fuel, :integer
    add_column :aplcat_parameters, :ninteen_area, :integer
    add_column :aplcat_parameters, :ninteen_equip, :integer
    add_column :aplcat_parameters, :ninteen_fuel, :integer
    add_column :aplcat_parameters, :twenty_area, :integer
    add_column :aplcat_parameters, :twenty_equip, :integer
    add_column :aplcat_parameters, :twenty_fuel, :integer
  end
end
