class CreateAplcatParameters < ActiveRecord::Migration[5.2]
  def change
    create_table :aplcat_parameters do |t|
      t.integer :noc
      t.integer :nomb
      t.integer :norh
      t.integer :nocrh
      t.float :prh
      t.float :prb
      t.float :abwc
      t.float :abwmb
      t.float :abwh
      t.float :abwrh
      t.float :adwgbc
      t.float :adwgbh
      t.integer :jdcc
      t.integer :gpc
      t.float :tpwg
      t.integer :csefa
      t.float :srop
      t.float :bwoc
      t.integer :jdbs
      t.integer :abc
      t.float :adwgbc_agp
      t.float :adwgbh_agp
      t.float :mrga
      t.integer :jdcc_agp
      t.integer :gpc_agp
      t.float :tpwg_agp
      t.integer :csefa_agp
      t.float :srop_agp
      t.float :bwoc_agp
      t.integer :jdbs_agp
      t.float :dmd
      t.float :dmi
      t.float :napanr
      t.float :napaip
      t.float :mpsm
      t.float :splm
      t.float :pmme
      t.integer :mm_type_amp
      t.float :fmbmm_amp
      t.float :rhaeba
      t.float :toaboba
      t.float :vsim_gp
      t.float :foue
      t.float :ash
      t.float :mmppfm
      t.float :cfmms
      t.float :fnemimms
      t.float :effn2ofmms
      t.float :dwawfga
      t.float :dwawflc
      t.float :dwawfmb
      t.float :pgu
      t.float :ada
      t.float :ape_wpp
      t.float :platc
      t.float :pctbb
      t.float :ptdife
      t.float :mrgauh
      t.integer :plac
      t.integer :pcbb
      t.float :fmbmm
      t.integer :domd
      t.float :vsim
      t.float :faueea
      t.float :acim
      t.float :mmppm
      t.float :cffm
      t.float :fnemm
      t.float :effd
      t.float :ptbd
      t.float :pocib
      t.float :bneap
      t.float :cneap
      t.float :hneap
      t.float :pobw
      t.float :posw
      t.float :posb
      t.float :poad
      t.float :poada
      t.float :cibo
      t.integer :mdogfc
      t.integer :mxdogfc
      t.integer :cwsoj
      t.integer :cweoj
      t.integer :nodew
      t.integer :byosm
      t.integer :eyosm
      t.float :drinkg
      t.float :drinkl
      t.float :drinkm
      t.float :tjan
      t.float :tfeb
      t.float :tmar
      t.float :tapr
      t.float :tmay
      t.float :tjun
      t.float :tjul
      t.float :taug
      t.float :tsep
      t.float :toct
      t.float :tnov
      t.float :tdec
      t.float :hjan
      t.float :hfeb
      t.float :hmar
      t.float :hapr
      t.float :hmay
      t.float :hjun
      t.float :hjul
      t.float :haug
      t.float :hsep
      t.float :hoct
      t.float :hnov
      t.float :hdec
      t.integer :rhae
      t.float :tabo
      t.integer :mpism
      t.integer :spilm
      t.integer :pom
      t.float :srinr
      t.float :sriip
      t.float :pogu
      t.integer :adoa
      t.float :ape
      t.integer :forage_id
      t.integer :jincrease
      t.integer :stabilization
      t.integer :decline
      t.integer :opt4
      t.float :cpl_lowest
      t.float :cpl_highest
      t.float :tdn_lowest
      t.float :tdn_highest
      t.float :ndf_lowest
      t.float :ndf_highest
      t.float :adf_lowest
      t.float :adf_highest
      t.float :fir_lowest
      t.float :fir_highest
      t.integer :categories_trans_1
      t.float :categories_slaug_1
      t.integer :avg_marweight_1
      t.integer :num_animal_1
      t.integer :second_avg_marweight_1
      t.integer :second_num_animal_1
      t.float :mortality_rate_1
      t.float :distance_1
      t.string :trailer_1
      t.string :trucks_1
      t.string :fuel_type_1
      t.float :carcass_1
      t.float :boneless_beef_1
      t.integer :categories_trans_2
      t.float :categories_slaug_2
      t.integer :avg_marweight_2
      t.integer :num_animal_2
      t.integer :second_avg_marweight_2
      t.integer :second_num_animal_2
      t.float :mortality_rate_2
      t.float :distance_2
      t.string :trailer_2
      t.string :trucks_2
      t.string :fuel_type_2
      t.float :carcass_2
      t.float :boneless_beef_2
      t.integer :categories_trans_3
      t.float :categories_slaug_3
      t.integer :avg_marweight_3
      t.integer :num_animal_3
      t.integer :second_avg_marweight_3
      t.integer :second_num_animal_3
      t.float :mortality_rate_3
      t.float :distance_3
      t.string :trailer_3
      t.string :trucks_3
      t.string :fuel_type_3
      t.float :carcass_3
      t.float :boneless_beef_3
      t.integer :categories_trans_4
      t.float :categories_slaug_4
      t.integer :avg_marweight_4
      t.integer :num_animal_4
      t.integer :second_avg_marweight_4
      t.integer :second_num_animal_4
      t.float :mortality_rate_4
      t.float :distance_4
      t.string :trailer_4
      t.string :trucks_4
      t.string :fuel_type_4
      t.float :carcass_4
      t.float :boneless_beef_4
      t.integer :tripn
      t.integer :freqtrip
      t.string :filedetails
      t.string :purpose
      t.integer :n_tfa
      t.integer :n_sr
      t.integer :n_arnfa
      t.integer :n_arpfa
      t.integer :n_nfar
      t.integer :n_npfar
      t.integer :n_co2enfp
      t.integer :n_co2enfa
      t.integer :n_co2epfp
      t.integer :n_lamf
      t.integer :n_lan2of
      t.integer :n_laco2f
      t.integer :n_socc
      t.integer :i_tfa
      t.integer :i_sr
      t.integer :i_arnfa
      t.integer :i_arpfa
      t.integer :i_nfar
      t.integer :i_npfar
      t.integer :i_co2enfp
      t.integer :i_co2enfa
      t.integer :i_co2epfp
      t.integer :i_lamf
      t.integer :i_lan2of
      t.integer :i_laco2f
      t.integer :i_socc
      t.integer :theta
      t.integer :fge
      t.integer :fde
      t.integer :first_area
      t.integer :first_equip
      t.integer :second_area
      t.integer :second_equip
      t.integer :third_area
      t.integer :third_equip
      t.integer :fourth_area
      t.integer :fourth_equip
      t.integer :fifth_area
      t.integer :fifth_equip

      t.timestamps
    end
  end
end
